// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zffzgytqzamacekpikpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpmZnpneXRxemFtYWNla3Bpa3BuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4MTMzNTgsImV4cCI6MjA2MjM4OTM1OH0.UjPU5px86LtAISffMJsihikaYsgmbWizOqStEY3_iT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);